package v1.entities.user;

public enum Country {
    AFGHANISTAN("AF", "Afghanistan"),
    ALAND_ISLANDS("AX", "Åland Islands"),
    ALBANIA("AL", "Albania"),
    ALGERIA("DZ", "Algeria"),
    AMERICAN_SAMOA("AS", "American Samoa"),
    ANDORRA("AD", "Andorra"),
    ANGOLA("AO", "Angola"),
    ANGUILLA("AI", "Anguilla"),
    ANTARCTICA("AQ", "Antarctica"),
    ANTIGUA_AND_BARBUDA("AG", "Antigua and Barbuda"),
    ARGENTINA("AR", "Argentina"),
    ARMENIA("AM", "Armenia"),
    ARUBA("AW", "Aruba"),
    AUSTRALIA("AU", "Australia"),
    AUSTRIA("AT", "Austria"),
    AZERBAIJAN("AZ", "Azerbaijan"),
    BAHAMAS("BS", "Bahamas"),
    BAHRAIN("BH", "Bahrain"),
    BANGLADESH("BD", "Bangladesh"),
    BARBADOS("BB", "Barbados"),
    BELARUS("BY", "Belarus"),
    BELGIUM("BE", "Belgium"),
    BELIZE("BZ", "Belize"),
    BENIN("BJ", "Benin"),
    BERMUDA("BM", "Bermuda"),
    BHUTAN("BT", "Bhutan"),
    PLURINATIONAL_STATE_OF_BOLIVIA("BO", "Plurinational state of Bolivia"),
    SINT_EUSTATIUS_AND_SABA_ABONAIRE("BQ", "Sint Eustatius and Saba Bonaire"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bosnia and Herzegovina"),
    BOTSWANA("BW", "Botswana"),
    BOUVET_ISLAND("BV", "Bouvet Island"),
    BRAZIL("BR", "BRAZIL"),
    BRITISH_INDIAN_OCEAN_TERRITORY("IO", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("BN", "Brunei Darussalam"),
    BULGARIA("BG", "Bulgaria"),
    BURKINA_FASO("BF", "Burkina Faso"),
    BURUNDI("BI", "burundi"),
    CAMBODIA("KH", "Cambodia"),
    CAMEROON("CM", "Cameroon"),
    CANADA("CA", "Canada"),
    CAPE_VERDE("CV", "Cape Verde"),
    CAYMAN_ISLANDS("KY", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "Central African Republic"),
    CHAD("TD", "Chad"),
    CHILE("CL", "Chile"),
    CHINA("CN", "China"),
    CHRISTMAS_ISLAND("CX", "Christmas Island"),
    COCOS_KEELING_ISLANDS("CC", "Cocos (Keeling) Islands"),
    COLOMBIA("CO", "Colombia"),
    COMOROS("KM", "Comoros"),
    CONGO("CG", "Congo"),
    THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO("CD", "The democratic republic of the Congo"),
    COOK_ISLANDS("CK", "Cook Islands"),
    COSTA_RICA("CR", "Costa Rica"),
    COTE_DIVOIRE("CI", "Côte d'Ivoire"),
    CROATIA("HR", "Croatia"),
    CUBA("CU", "Cuba"),
    CURACAO("CW", "Curaçao"),
    CYPRUS("CY", "Cyprus"),
    CZECH_REPUBLIC("CZ", "Czech Republic"),
    DENMARK("DK", "Denmark"),
    DJIBOUTI("DJ", "Djibouti"),
    DOMINICA("DM", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "Dominican Republic"),
    ECUADOR("EC", "Ecuador"),
    EGYPT("EG", "Egypt"),
    EL_SALVADOR("SV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "Equatorial guinea"),
    ERITREA("ER", "Eritrea"),
    ESTONIA("EE", "Estonia"),
    ETHIOPIA("ET", "Ethiopia"),
    FALKLAND_ISLANDS_MALVINAS("FK", "Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("FO", "Faroe Islands"),
    FIJI("FJ", "Fiji"),
    FINLAND("FI", "Finland"),
    FRANCE("FR", "France"),
    FRENCH_GUIANA("GF", "French Guiana"),
    FRENCH_POLYNESIA("PF", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("TF", "French Southern Territories"),
    GABON("GA", "Gabon"),
    GAMBIA("GM", "Gambia"),
    GEORGIA("GE", "Georgia"),
    GERMANY("DE", "Germany"),
    GHANA("GH", "Ghana"),
    GIBRALTAR("GI", "Gibraltar"),
    GREECE("GR", "Greece"),
    GREENLAND("GL", "Greenland"),
    GRENADA("GD", "Grenada"),
    GUADELOUPE("GP", "Guadeloupe"),
    GUAM("GU", "Guam"),
    GUATEMALA("GT", "Guatemala"),
    GUERNSEY("GG", "Guernsey"),
    GUINEA("GN", "Guinea"),
    GUINEA_BISSAU("GW", "Guinea-Bissau"),
    GUYANA("GY", "Guyana"),
    HAITI("HT", "Haiti"),
    HEARD_ISLAND_ANd_MCDONALD_ISLANDS("HM", "Heard Island and Mcdonald Islands"),
    HOLY_SEE_VATICAN_CITY_STATE("VA", "Holy See (Vatican City State)"),
    HONDURAS("HN", "Honduras"),
    HONG_KONG("HK", "Hong Kong"),
    HUNGARY("HU", "Hungary"),
    ICELAND("IS", "Iceland"),
    INDIA("IN", "India"),
    INDONESIA("ID", "Indonesia"),
    ISLAMIC_REPUBLIC_OF_IRAN("IR", "Islamic Republic of Iran"),
    IRAQ("IQ", "Iraq"),
    IRELAND("IE", "Ireland"),
    ISLE_OF_MAN("IM", "Isle Of Man"),
    ISRAEL("IL", "Israel"),
    ITALY("IT", "Italy"),
    JAMAICA("JM", "Jamaica"),
    JAPAN("JP", "Japan"),
    JERSEY("JE", "Jersey"),
    JORDAN("JO", "Jordan"),
    KAZAKHSTAN("KZ", "KAzakhstan"),
    KENYA("KE", "Kenya"),
    KIRIBATI("KI", "Kiribati"),
    DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA("KP", "Democratic People's Republic of Korea"),
    REPUBLIC_OF_KOREA("KR", "Republic of Korea"),
    KUWAIT("KW", "Kuwait"),
    KYRGYZSTAN("KG", "Kyrgyzstan"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("LA", "Lao Peoples Democratic Republic"),
    LATVIA("LV", "Latvia"),
    LEBANON("LB", "Lebanon"),
    LESOTHO("LS", "Lesotho"),
    LIBERIA("LR", "Liberia"),
    LIBYA("LY", "Libya"),
    LIECHTENSTEIN("LI", "Liechtenstein"),
    LITHUANIA("LT", "Lithuania"),
    LUXEMBOURG("LU", "Luxembourg"),
    MACAO("MO", "Macao"),
    THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA("MK", "The former Yugoslav Republic of Macedonia"),
    MADAGASCAR("MG", "Madagascar"),
    MALAWI("MW", "MAlawi"),
    MALAYSIA("MY", "Malaysia"),
    MALDIVES("MV", "MAldives"),
    MALI("ML", "Mali"),
    MALTA("MT", "Malta"),
    MARSHALL_ISLANDS("MH", "Marshall Islands"),
    MARTINIQUE("MQ", "Martinique"),
    MAURITANIA("MR", "Mauritania"),
    MAURITIUS("MU", "Mauritius"),
    MAYOTTE("YT", "Mayotte"),
    MEXICO("MX", "Mexico"),
    FEDERATED_STATES_OF_MICRONESIA("FM", "Federated States of Micronesia"),
    REPUBLIC_OF_MOLDOVA("MD", "Republic of Moldova"),
    MONACO("MC", "Monaco"),
    MONGOLIA("MN", "Mongolia"),
    MONTENEGRO("ME", "Montenegro"),
    MONTSERRAT("MS", "Montserrat"),
    MOROCCO("MA", "Morocco"),
    MOZAMBIQUE("MZ", "Mozambique"),
    MYANMAR("MM", "Myanmar"),
    NAMIBIA("NA", "Namibia"),
    NAURU("NR", "Nauru"),
    NEPAL("NP", "Nepal"),
    NETHERLANDS("NL", "Netherlands"),
    NEW_CALEDONIA("NC", "New Caledonia"),
    NEW_ZEALAND("NZ", "New Zealand"),
    NICARAGUA("NI", "Nicaragua"),
    NIGER("NE", "Niger"),
    NIGERIA("NG", "Nigeria"),
    NIUE("NU", "Niue"),
    NORFOLK_ISLAND("NF", "Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("MP", "Northern Mariana Islands"),
    NORWAY("NO", "Norway"),
    OMAN("OM", "Oman"),
    PAKISTAN("PK", "Pakistan"),
    PALAU("PW", "Palau"),
    STATE_OF_PALESTINE("PS", "State of Palestine"),
    PANAMA("PA", "Panama"),
    PAPUA_NEW_GUINEA("PG", "Papua New Guinea"),
    PARAGUAY("PY", "Paraguay"),
    PERU("PE", "Peru"),
    PHILIPPINES("PH", "Philippines"),
    PITCAIRN("PN", "Pitcairn"),
    POLAND("PL", "Poland"),
    PORTUGAL("PT", "Portugal"),
    PUERTO_RICO("PR", "Puerto rico"),
    QATAR("QA", "Qatar"),
    REUNION("RE", "Réunion"),
    ROMANIA("RO", "Romania"),
    RUSSIAN_FEDERATION("RU", "Russian Federation"),
    RWANDA("RW", "Rwanda"),
    SAINT_BARTHELEMY("BL", "Saint Barthélemy"),
    ASCENSION_AND_TRISTAN_DA_CUNHA_SAINT_HELENA("SH", "Ascension and Tristan Da Cunha Saint Helena"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts and Nevis"),
    SAINT_LUCIA("LC", "Saint Lucia"),
    SAINT_MARTIN_FRENCH_PART("MF", "Saint Martin (French part)"),
    SAINT_PIERRE_AND_MIQUELON("PM", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent and the Grenadines"),
    SAMOA("WS", "Samoa"),
    SAN_MARINO("SM", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "Sao Tome and Principe"),
    SAUDI_ARABIA("SA", "Saudi Arabia"),
    SENEGAL("SN", "Senegal"),
    SERBIA("RS", "Serbia"),
    SEYCHELLES("SC", "Seychelles"),
    SIERRA_LEONE("SL", "Sierra Leone"),
    SINGAPORE("SG", "Singepore"),
    SINT_MAARTEN_DUTCH_PART("SX", "Sint Maarten (Dutch part)"),
    SLOVAKIA("SK", "Slovakia"),
    SLOVENIA("SI", "Slovenia"),
    SOLOMON_ISLANDS("SB", "Solomon Islands"),
    SOMALIA("SO", "Somalia"),
    SOUTH_AFRICA("ZA", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("GS", "South Georgia and the South Sandwich Islands"),
    SOUTH_SUDAN("SS", "South Sudan"),
    SPAIN("ES", "Spain"),
    SRI_LANKA("LK", "Sri Lanka"),
    SUDAN("SD", "Sudan"),
    SURINAME("SR", "Suriname"),
    SVALBARD_AND_JAN_MAYEN("SJ", "Svalbard and Jan Mayen"),
    SWAZILAND("SZ", "Swaziland"),
    SWEDEN("SE", "Sweden"),
    SWITZERLAND("CH", "Switzerland"),
    SYRIAN_ARAB_REPUBLIC("SY", "Syrian Arab Republic"),
    PROVINCE_OF_CHINA_TAIWAN("TW", "Province of China Taiwan"),
    TAJIKISTAN("TJ", "Tajikistan"),
    UNITED_REPUBLIC_OF_TANZANIA("TZ", "United Republic of Tanzania"),
    THAILAND("TH", "Thailand"),
    TIMOR_LESTE("TL", "Timor-Leste"),
    TOGO("TG", "Togo"),
    TOKELAU("TK", "Tokelau"),
    TONGA("TO", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "Trinidad and Tobago"),
    TUNISIA("TN", "Tunisia"),
    TURKEY("TR", "Turkey"),
    TURKMENISTAN("TM", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("TC", "Turks and Caicos Islands"),
    TUVALU("TV", "Tuvalu"),
    UGANDA("UG", "Uganda"),
    UKRAINE("UA", "Ukraine"),
    UNITED_ARAB_EMIRATES("AE", "United Arab Emirates"),
    UNITED_KINGDOM("GB", "United Kingdom"),
    UNITED_STATES("US", "United States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "United States Minor Outlying Islands"),
    URUGUAY("UY", "Uruguay"),
    UZBEKISTAN("UZ", "Uzbekistan"),
    VANUATU("VU", "Vanuatu"),
    BOLIVARIAN_REPUBLIC_OF_VENEZUELA("VE", "Bolivarian Republic of Venezuela"),
    VIET_NAM("VN", "Viet nam"),
    VIRGIN_ISLANDS_BRITISH("VG", "Virgin Islands, British"),
    VIRGIN_ISLANDS_US("VI", "Virgin islands, U.S."),
    WALLIS_AND_FUTUNA("WF", "Wallis and Futuna"),
    WESTERN_SAHARA("EH", "Western Sahara"),
    YEMEN("YE", "Yemen"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABWE("ZW", "Zimbabwe");


    String abbreviation;
    String countryName;

    Country(String abbreviation, String countryName) {
        this.abbreviation = abbreviation;
        this.countryName = countryName;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public String getCountryName() {
        return countryName;
    }

    public static Country getByAbbreviation(String abbreviation) {
        for (Country country : Country.values()) {
            if (country.getAbbreviation().equals(abbreviation)) {
                return country;
            }
        }
        throw new NullPointerException();
    }


}